platform :ios, '8.0'
use_frameworks!
#私有库
source'https://code.aliyun.com/hengyang.king/MusicHomeSpecs.git'
#公有库
source'https://github.com/CocoaPods/Specs.git' 

target 'MHPhotoBroswerDemo' do
  pod 'MHPhotoBroswer', :path =>'../'

end
